# Site settings
title: "中国画数据集"
email: "276554196@qq.com"
description: > # this means to ignore newlines until "baseurl:"
Chinese painting dataset classification
baseurl: "/painting" # the subpath of your site, e.g. /blog/
url: "http://whoohoo.github.io" # the base hostname & protocol for your site

github_username:  whoohoo

# Build settings
markdown: kramdown
permalink: pretty
