# Site settings
title: "中国画数据集"
email: "276554196@qq.com"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/painting" # the subpath of your site, e.g. /blog/
url: "http://whoohoo.github.io" # the base hostname & protocol for your site

github_username:  whoohoo

# Build settings
markdown: kramdown
permalink: pretty
