# Site settings
title: "中国画数据集"
email: "276554196@qq.com"
description: > # this means to ignore newlines until "baseurl:"
  Chinese painting data set classification.
baseurl: "/painting" # the subpath of your site, e.g. /blog/
url: "http://whoohoo.github.io" # the base hostname & protocol for your site
twitter_username: zhjingyxxx
github_username:  whoohoo

# Build settings
markdown: kramdown
permalink: pretty
